/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloTense */

#ifndef _Included_HelloTense
#define _Included_HelloTense
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloTense
 * Method:    initialise
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_HelloTense_initialise
  (JNIEnv *, jobject);

/*
 * Class:     HelloTense
 * Method:    destroy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_HelloTense_destroy
  (JNIEnv *, jobject);

/*
 * Class:     HelloTense
 * Method:    health_check
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloTense_health_1check
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
